### ISSUE TITLE
Contest Editorials just contain solution file, and are missing on the exact problem statement(s) per solution

### ISSUE THREAD

**Issue by Git-Harshit** [Brainless-Coders/CP-Buddy-Series#27]
The editorials just contain are code files, with no description or reference to the entire problem. I believe having entire question per problem or atleast a unique link to the questions/contest will be really helpful for future references.

Please consider adding relevant content or links as a Questionnaire.md file or at any description or common reference as README.md file.

**Comment by adad20** [comment]
@Git-Harshit Thats nice suggestion would you like to work on this for any 1 week?

**Comment by Git-Harshit** [comment]
> Btw we added the contest link in the particular week's readme.md file. 
@adad20 Yes! You're right! My bad, I didn't notice that before. My apologies for incorrect suggestion! 

> Thats nice suggestion would you like to work on this for any 1 week?
Sure, I can do it! I'll try linking contest-specific questions or contest link for every folder containing a contest solution, in parts. I'd love to get assistance as well for the same. 😄 

Then, this issue may be closed.

**Comment by adad20** [comment]
@Git-Harshit If we feel the need to add problem statement in solution I will reopen this.

And we added that before but we stopped that because we want students to first solve by their own then see the solution otherwise they directly go to editorials
